import { Link } from 'react-router-dom'
import { Badge } from '@/components/ui/primitives'
import { Note } from '@/components/code'
import { H2, PageHeader, useHeadings } from '@/components/docs-layout'

interface UseCase {
  title: string
  problem: string
  how: string
  calls: string[]
  note?: string
}

const GROUPS: { id: string; title: string; blurb: string; cases: UseCase[] }[] = [
  {
    id: 'documents',
    title: 'Document workflows',
    blurb:
      'Anything where a person receives a PDF, changes part of it, and sends it back. These are the cases the library was designed around.',
    cases: [
      {
        title: 'Correct a typo without regenerating the file',
        problem:
          'A contract went out with a misspelt name. The source document is in someone else’s hands, or was generated by a system nobody wants to run again.',
        how: 'Find the paragraph, replace the characters, commit. The other 200 pages keep their exact bytes, so signatures on unrelated revisions and any downstream hash of the untouched objects stay valid.',
        calls: ['page()', 'replaceText()', 'commit()'],
      },
      {
        title: 'Fill a form nobody has the source for',
        problem:
          'A government or bank PDF with AcroForm fields. Filling it in a viewer works; doing it for ten thousand applicants does not.',
        how: 'Read the field tree, set values by fully qualified name, flatten so the values cannot be edited back out.',
        calls: ['formFields()', 'setFieldValue()', 'flattenForms()'],
      },
      {
        title: 'Redact before disclosure',
        problem:
          'A document has to go out with names, account numbers or addresses removed, and a black rectangle drawn over text is not removal.',
        how: 'Remove the glyphs, then ask the library to search the saved bytes for the string. Redaction forces a full rewrite so the original bytes cannot survive in an earlier revision.',
        calls: ['redactText()', 'verifyRedaction()'],
        note: 'Read notChecked as well as clean. It names the places the check does not reach.',
      },
      {
        title: 'Merge, split and reorder',
        problem: 'Assemble a submission pack from several files, or pull one chapter out of a report.',
        how: 'Delete and reorder pages with links, outlines and named destinations retargeted rather than left dangling.',
        calls: ['deletePage()', 'movePage()'],
      },
      {
        title: 'Stamp every page with a reference',
        problem: 'Case numbers, Bates numbers, draft watermarks, a recipient name on each page.',
        how: 'Add an annotation per page, or compose the mark and place it. Adding content appends a stream rather than rewriting the page, so nothing already on the page moves.',
        calls: ['addAnnotation()', 'save()'],
      },
      {
        title: 'Update a price list in place',
        problem: 'A catalogue is regenerated monthly, but only the numbers change.',
        how: 'Locate the table, set cell values, and let the reflow policy decide whether the column widens or the text shrinks.',
        calls: ['page().tables', 'setCellText()'],
      },
    ],
  },
  {
    id: 'generation',
    title: 'Generation',
    blurb:
      'Composing documents that did not exist. The layout engine handles measure, leading, pagination and columns; the typeface is embedded and subset to what you actually draw.',
    cases: [
      {
        title: 'Invoices, receipts and statements',
        problem:
          'Server-side PDF generation means a headless browser or a print pipeline. Both are heavy, and both fail in ways that are hard to reproduce.',
        how: 'Describe the content as blocks and compose it in the tab or in a Worker. No browser, no font installed on the host, no network.',
        calls: ['Pdf.create()'],
      },
      {
        title: 'Reports and exports from application data',
        problem: 'Users want the dashboard as a PDF, and the screenshot approach produces something nobody can select text in.',
        how: 'Compose from the same data that drives the view. The text is real text, so it is searchable, copyable and accessible.',
        calls: ['Pdf.create()', 'save()'],
      },
      {
        title: 'Certificates and letters at volume',
        problem: 'Ten thousand personalised documents, each with a different name and date.',
        how: 'Compose each one. The font is embedded once per document and subset to the glyphs that document uses, so a name in Greek costs only the glyphs in that name.',
        calls: ['Pdf.create()'],
        note: 'Composition picks a Type0 font automatically when the text needs one.',
      },
      {
        title: 'Offline-first and privacy-sensitive generation',
        problem:
          'Medical, legal or financial content that must not leave the device, or a field application with no connectivity.',
        how: 'Everything runs in WebAssembly in the tab. No document is uploaded, because there is nowhere to upload it to.',
        calls: ['Pdf.create()'],
      },
    ],
  },
  {
    id: 'pipelines',
    title: 'Pipelines and automation',
    blurb: 'Server-side and batch work, where the Rust crates are the better entry point.',
    cases: [
      {
        title: 'Normalise files from many producers',
        problem:
          'Documents arrive from scanners, Word, InDesign, LaTeX and a decade of legacy tooling. Half of them break something.',
        how: 'Open with recovery enabled, read the leniency list to see what was wrong, and re-save clean. The recovery path rebuilds a cross-reference table by scanning when the real one is unusable.',
        calls: ['open({ recovery })', 'info().leniencies'],
      },
      {
        title: 'Extract text and structure for search or a model',
        problem: 'Indexing, retrieval, or feeding documents to a language model.',
        how: 'Read paragraphs in reading order rather than content order, with tables as tables and headers and footers separated from the body.',
        calls: ['page().paragraphs', 'page().tables'],
        note: 'Reading order comes from the structure tree when the document has one, and from geometry when it does not. Which one was used is reported.',
      },
      {
        title: 'Prune bloated files',
        problem: 'A 40 MB document where 35 MB is fonts nobody uses any more after edits.',
        how: 'Drop every glyph no page draws from each embedded font, then save a full rewrite.',
        calls: ['compactFonts()', 'save({ mode: "full-rewrite" })'],
      },
      {
        title: 'Audit and compliance checks',
        problem: 'Confirm a batch is tagged, has no XFA, carries no JavaScript, and is not encrypted in a way that blocks accessibility.',
        how: 'Every one of those is a property on the info object or a leniency, and none of them needs the document rendered.',
        calls: ['info()', 'metadata()'],
      },
      {
        title: 'Re-encrypt or remove protection',
        problem: 'A vault holds files under a rotated password, or a document has to be decrypted for archival.',
        how: 'Open with the password, change or drop protection, save. Changing protection forces a full rewrite because a mixed-key file is unreadable.',
        calls: ['protect()', 'unprotect()'],
      },
    ],
  },
  {
    id: 'products',
    title: 'Products you could build on it',
    blurb: 'Larger shapes, where the library is the engine rather than a utility.',
    cases: [
      {
        title: 'A browser-based PDF editor',
        problem:
          'Every web editor either renders and overlays, or uploads the file to a server that runs a desktop tool.',
        how: 'Pair pdf.js for display with Rasura for editing. The editor on this site does the second half without the first, to show what the library alone knows.',
        calls: ['everything'],
      },
      {
        title: 'Translation and localisation tooling',
        problem: 'Translating a laid-out document usually means rebuilding it, because the text grows.',
        how: 'Replace paragraph text and let reflow re-break the lines at the measure the document used. Overflow is reported rather than clipped, so a string that no longer fits is a decision rather than a surprise.',
        calls: ['replaceText()', 'configureSession({ overflow })'],
      },
      {
        title: 'Accessibility remediation',
        problem: 'A tagged document loses its tags the moment anything edits it.',
        how: 'Tag integrity is an invariant here, checked across the corpus on every run. Editing a tagged document keeps the structure tree consistent, and degradation is reported separately from absence.',
        calls: ['info().taggedStatus'],
      },
      {
        title: 'Document diffing and review',
        problem: 'Two revisions of a contract, and the question is what changed.',
        how: 'Compare reconstructed paragraph text rather than rendered pixels, so a reflow that moved every line does not read as a change on every line.',
        calls: ['page().paragraphs'],
      },
      {
        title: 'Data extraction from forms and invoices',
        problem: 'Pulling line items out of thousands of supplier invoices.',
        how: 'Tables are detected with cell geometry, so a row is a row rather than a cluster of text at similar y positions.',
        calls: ['page().tables'],
      },
      {
        title: 'Regulated archival',
        problem: 'Files must be verifiably unmodified except for a recorded set of changes.',
        how: 'Incremental saving keeps every prior revision in the file. What changed is the appended bytes, and what did not is identical.',
        calls: ['save()', 'info().revisionCount'],
      },
    ],
  },
]

export default function UseCases() {
  useHeadings(GROUPS.map((g) => ({ id: g.id, text: g.title, level: 2 as const })))

  return (
    <>
      <PageHeader
        title="Use cases"
        summary="Twenty-one things people build with this, what makes each one hard, and the calls it needs."
      />

      <p>
        The common thread is that all of them need the document to survive. Anything that
        regenerates the file loses signatures, revision history, tags, and every byte
        someone downstream might be hashing.
      </p>

      {GROUPS.map((group) => (
        <section key={group.id} className="mt-10">
          <H2 id={group.id}>{group.title}</H2>
          <p>{group.blurb}</p>
          <div className="not-prose mt-5 flex flex-col gap-3">
            {group.cases.map((c) => (
              <Case key={c.title} {...c} />
            ))}
          </div>
        </section>
      ))}

      <Note kind="info" title="Not on this list">
        Anything that needs the page rasterised: thumbnails, print preview, OCR of a scan.
        Rasura has no renderer. Pair it with pdf.js, which does that well.
      </Note>

      <p className="mt-6">
        If your case is not here, the <Link to="/api">API reference</Link> lists every
        operation, and most workflows are two or three of them in sequence.
      </p>
    </>
  )
}

function Case({ title, problem, how, calls, note }: UseCase) {
  return (
    <div className="rounded-lg border border-border bg-card p-4">
      <p className="text-[14px] font-semibold tracking-tight">{title}</p>
      <p className="mt-1.5 text-[13px] leading-relaxed text-muted-foreground">{problem}</p>
      <p className="mt-2 text-[13px] leading-relaxed">{how}</p>
      {note && (
        <p className="mt-2 border-l-2 border-warning/40 pl-2.5 text-[12.5px] text-muted-foreground">
          {note}
        </p>
      )}
      <div className="mt-3 flex flex-wrap gap-1.5">
        {calls.map((call) => (
          <Badge key={call} variant="outline" className="font-mono">
            {call}
          </Badge>
        ))}
      </div>
    </div>
  )
}
