//! The reshape boundary rule. Spec 8.3.
//!
//! > Only reshape the minimal span that contains the edit, expanded outward to
//! > the nearest word boundaries on both sides, and never beyond the enclosing
//! > line. Glyphs outside that span keep their original GIDs and positions
//! > byte-for-byte.
//!
//! The reason is worth stating plainly, because the rule looks like an
//! optimisation and is not. A PDF stores **post-shaping glyph ids**: the
//! producer ran some shaper, at some version, with some features, and recorded
//! the result. Nothing in the file says which. Reshaping a whole line with
//! `rustybuzz` would therefore rewrite glyphs the user never touched, using a
//! shaper that may legitimately disagree with the original about ligatures,
//! kerning or mark placement — and §2 forbids exactly that: an edit must not
//! change output it did not need to change.
//!
//! So the blast radius of a shaper disagreement is bounded to the words the
//! user actually edited. Everything else is copied.
//!
//! This module is pure index arithmetic and holds no font data, which is
//! deliberate: it is the part of §8.3 that decides what gets rewritten, and it
//! should be testable without a font.

use std::ops::Range;

/// Where a reshape may write.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReshapeSpan {
    /// Glyph indices within the line that will be re-shaped and may change.
    pub span: Range<usize>,
    /// Whether the span had to be widened beyond the edit itself.
    pub widened: bool,
    /// Whether the span reaches the whole line, so nothing is preserved.
    pub whole_line: bool,
}

impl ReshapeSpan {
    /// Glyphs before the span, which keep their original ids and positions.
    pub fn preserved_before(&self) -> Range<usize> {
        0..self.span.start
    }

    /// Glyphs after the span, likewise.
    pub fn preserved_after(&self, line_len: usize) -> Range<usize> {
        self.span.end.min(line_len)..line_len
    }

    pub fn len(&self) -> usize {
        self.span.len()
    }

    pub fn is_empty(&self) -> bool {
        self.span.is_empty()
    }
}

/// Compute the span to reshape for an edit.
///
/// `boundaries` are glyph indices at which a word starts, as §7.4 segments
/// them; index 0 is always a boundary whether or not it is listed. `edit` is
/// the half-open glyph range the edit touches, and `line_len` bounds
/// everything.
///
/// An insertion is an empty range at the insertion point; it still expands to
/// the surrounding word, because inserting a character mid-word can change how
/// the whole word shapes.
pub fn span_for(edit: Range<usize>, boundaries: &[usize], line_len: usize) -> ReshapeSpan {
    if line_len == 0 {
        return ReshapeSpan { span: 0..0, widened: false, whole_line: true };
    }

    let start = edit.start.min(line_len);
    let end = edit.end.clamp(start, line_len);

    // Expand left to the word start at or before the edit.
    let left =
        boundaries.iter().copied().filter(|b| *b <= start && *b < line_len).max().unwrap_or(0);

    // Expand right to the next word start strictly after the edit -- that
    // index is the first glyph of the following word, so it is the exclusive
    // end of ours. An edit touching the last word runs to the line's end.
    //
    // `> end` rather than `>= end`: a boundary exactly at `end` would end the
    // span at the edit's own last glyph and leave the rest of that word
    // unshaped, which is the off-by-one this rule exists to avoid.
    let right =
        boundaries.iter().copied().filter(|b| *b > end && *b <= line_len).min().unwrap_or(line_len);

    let span = left..right.max(left);
    ReshapeSpan {
        widened: span.start != start || span.end != end,
        whole_line: span.start == 0 && span.end >= line_len,
        span,
    }
}

/// Whether the producer applied the font's own kerning, inferred from the
/// positioning the file already contains. Spec 8.3.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KerningSource {
    /// `TJ` adjustments match the font's own kern values: the producer used
    /// font kerning and a reshape should too.
    Font,
    /// Adjustments are present but do not match the font, so they are the
    /// producer's own tracking and must be preserved rather than regenerated.
    Producer,
    /// No adjustments at all.
    None,
}

/// Classify the kerning in a run.
///
/// `observed` are the `TJ` adjustments actually in the file, in glyph-space
/// units with the PDF's sign convention already removed, paired with the
/// font's kern value for the same pair. A pair the font does not kern
/// contributes `None`.
///
/// The distinction matters because the two cases call for opposite treatment:
/// font kerning should be regenerated by the shaper, and producer tracking must
/// be carried through untouched, or the text will visibly respace.
pub fn kerning_source(observed: &[(f64, Option<f64>)]) -> KerningSource {
    const TOLERANCE: f64 = 1.0;

    let adjusted: Vec<&(f64, Option<f64>)> =
        observed.iter().filter(|(v, _)| v.abs() > f64::EPSILON).collect();
    if adjusted.is_empty() {
        return KerningSource::None;
    }

    let matching = adjusted
        .iter()
        .filter(|(v, font)| font.is_some_and(|f| (v - f).abs() <= TOLERANCE))
        .count();

    // A clear majority, not merely some. A producer applying its own tracking
    // will coincide with the font's kern value on the odd pair by chance, and
    // regenerating on that evidence would respace the whole run.
    if matching * 2 > adjusted.len() { KerningSource::Font } else { KerningSource::Producer }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A line of 20 glyphs: words at 0, 5, 11 and 16.
    const BOUNDARIES: [usize; 4] = [0, 5, 11, 16];
    const LINE: usize = 20;

    #[test]
    fn an_edit_inside_a_word_expands_to_that_word() {
        let s = span_for(6..8, &BOUNDARIES, LINE);
        assert_eq!(s.span, 5..11);
        assert!(s.widened);
        assert!(!s.whole_line);
    }

    #[test]
    fn glyphs_outside_the_span_are_preserved() {
        // The whole point: everything else keeps its original ids byte for byte.
        let s = span_for(6..8, &BOUNDARIES, LINE);
        assert_eq!(s.preserved_before(), 0..5);
        assert_eq!(s.preserved_after(LINE), 11..20);
        assert_eq!(s.len(), 6);
    }

    #[test]
    fn an_edit_spanning_two_words_covers_both_whole() {
        let s = span_for(7..13, &BOUNDARIES, LINE);
        assert_eq!(s.span, 5..16, "from the start of word two to the end of word three");
    }

    #[test]
    fn an_edit_in_the_last_word_runs_to_the_line_end() {
        let s = span_for(17..18, &BOUNDARIES, LINE);
        assert_eq!(s.span, 16..20);
        assert!(!s.whole_line);
    }

    #[test]
    fn an_edit_in_the_first_word_starts_at_zero() {
        let s = span_for(1..2, &BOUNDARIES, LINE);
        assert_eq!(s.span, 0..5);
    }

    #[test]
    fn a_boundary_exactly_at_the_edit_end_does_not_truncate_the_word() {
        // The off-by-one this rule exists to avoid. An edit ending at 11 -- the
        // first glyph of word three -- must still reshape all of word three,
        // not stop at its first glyph.
        let s = span_for(6..11, &BOUNDARIES, LINE);
        assert_eq!(s.span, 5..16);
    }

    #[test]
    fn an_insertion_expands_to_the_surrounding_word() {
        // An empty range: inserting a character mid-word can change how the
        // whole word shapes, so the word is the unit either way.
        let s = span_for(7..7, &BOUNDARIES, LINE);
        assert_eq!(s.span, 5..11);
    }

    #[test]
    fn an_insertion_at_a_word_start_takes_that_word() {
        let s = span_for(5..5, &BOUNDARIES, LINE);
        assert_eq!(s.span, 5..11);
    }

    #[test]
    fn an_edit_covering_the_line_reshapes_all_of_it() {
        let s = span_for(0..LINE, &BOUNDARIES, LINE);
        assert_eq!(s.span, 0..LINE);
        assert!(s.whole_line);
        assert!(s.preserved_before().is_empty());
        assert!(s.preserved_after(LINE).is_empty());
    }

    #[test]
    fn the_span_never_leaves_the_line() {
        // Spec 8.3: "never beyond the enclosing line".
        for edit in [0..100, 50..60, 19..25] {
            let s = span_for(edit.clone(), &BOUNDARIES, LINE);
            assert!(s.span.end <= LINE, "{edit:?} produced {:?}", s.span);
            assert!(s.span.start <= s.span.end);
        }
    }

    #[test]
    fn a_line_with_no_boundaries_is_one_word() {
        let s = span_for(3..4, &[], LINE);
        assert_eq!(s.span, 0..LINE, "no segmentation means the line is the unit");
    }

    #[test]
    fn an_empty_line_yields_an_empty_span() {
        let s = span_for(0..0, &[], 0);
        assert!(s.is_empty());
    }

    // --- kerning provenance -------------------------------------------------

    #[test]
    fn no_adjustments_is_no_kerning() {
        assert_eq!(kerning_source(&[]), KerningSource::None);
        assert_eq!(kerning_source(&[(0.0, Some(-40.0)), (0.0, None)]), KerningSource::None);
    }

    #[test]
    fn adjustments_matching_the_font_are_font_kerning() {
        let observed = [(-40.0, Some(-40.0)), (-15.0, Some(-15.0)), (-80.0, Some(-80.5))];
        assert_eq!(kerning_source(&observed), KerningSource::Font);
    }

    #[test]
    fn adjustments_the_font_does_not_explain_are_the_producers() {
        // Uniform tracking: every pair adjusted by the same amount, which no
        // font's kern table does. Regenerating it would visibly respace the run.
        let observed = [(-25.0, None), (-25.0, Some(-40.0)), (-25.0, None), (-25.0, Some(0.0))];
        assert_eq!(kerning_source(&observed), KerningSource::Producer);
    }

    #[test]
    fn one_coincidental_match_is_not_font_kerning() {
        // A producer applying its own tracking will hit the font's value by
        // chance now and then; a clear majority is required, not merely some.
        let observed =
            [(-25.0, Some(-25.0)), (-25.0, Some(-40.0)), (-25.0, None), (-25.0, Some(-90.0))];
        assert_eq!(kerning_source(&observed), KerningSource::Producer);
    }
}
